### PR TITLE
try to catch scylla_prepare/irq setting error

### LINKED ISSUE #118: catch scylla_prepare/irq setting error
The irq setting error was ignored by scylla_prepare, it won't break scylla-server start.
But we need to fix it. Let's try to catch this error in artifact-test.

eg: 
```
[stdout] Jan 06 20:04:55 ip-172-30-0-113.ec2.internal scylla_prepare[13698]: Setting mask 00000001 in /proc/irq/205/smp_affinity
[stdout] Jan 06 20:04:55 ip-172-30-0-113.ec2.internal scylla_prepare[13698]: Restarting irqbalance via systemctl...
[stdout] Jan 06 20:04:55 ip-172-30-0-113.ec2.internal scylla_prepare[13698]: Failed to write into /proc/irq/205/smp_affinity: (<class 'OSError'>, OSError(5, 'Input/output error'), <traceback object at 0x7f636fffe
ec8>)
[stdout] Jan 06 20:04:55 ip-172-30-0-113.ec2.internal scylla_prepare[13698]: No non-NVMe disks to tune
[stdout] Jan 06 20:04:55 ip-172-30-0-113.ec2.internal scylla_prepare[13698]: Setting mask 00000001 in /proc/irq/333/smp_affinity
[stdout] Jan 06 20:04:55 ip-172-30-0-113.ec2.internal scylla_prepare[13698]: Setting NVMe disks: nvme5n1, nvme6n1, nvme4n1, nvme2n1, nvme7n1, nvme3n1, nvme1n1, nvme8n1...
[stdout] Jan 06 20:04:55 ip-172-30-0-113.ec2.internal scylla_prepare[13698]: Failed to write into /proc/irq/333/smp_affinity: (<class 'OSError'>, OSError(5, 'Input/output error'), <traceback object at 0x7f636fffeec8>)
```

### PR DESCRIPTION
**Pull request by amoskong**
Fixes #118

### CODE REVIEW

**Comment by amoskong** [comment]
There is a trello ticket related to nvme interrupt verify: https://trello.com/c/RcvhR4lA/510-add-verification-for-nvme-interrupts-in-ami-test

**Comment by amoskong** [comment]
Do you expect this PR also solve the trello ticket? or split to two PR?

**Comment by roydahan** [comment]
I thought this is to solve the Trello ticket.
I don't mind to split.

**Comment by amoskong** [comment]
I will use another PR for https://trello.com/c/RcvhR4lA/510-add-verification-for-nvme-interrupts-in-ami-test

We can review & merge this PR first.

**Pull request merged**
