### PR TITLE
add assert for housekeeping.uuid

### PR DESCRIPTION
**Pull request by amoskong**
Raise error when housekeeping.uuid doesn't exist

### CODE REVIEW

**Comment by amoskong** [comment]
All our running artifact-jobs support housekeeping by default, so this PR is fine.
Need more testing, I will include new PR to test.

Wait my test result before merging the PR.

**Comment by roydahan** [comment]
@amoskong to approve after testing.

**Comment by roydahan** [comment]
@amoskong, is this one still needed?

**Comment by amoskong** [comment]
This PR is necessary, it's safe during recent testing.

**Comment by amoskong** [comment]
Rebase to latest maser, and merge the PR.

**Pull request merged**
