### PR TITLE
enable extend repo for installing scylla

### PR DESCRIPTION
**Pull request by amoskong**
This is for master & branch-2.1

### CODE REVIEW

**Comment by slivne** [comment]
I can't find the additional ppa scylladb repo for ubuntu14/16 ?

**Comment by amoskong** [comment]
I thought we already added scylladb/ppa, but it's openjdk.  I will add
scylladb/ppa and retest.

**Comment by amoskong** [comment]
artifact-test of ubuntu 16 & 14 works well: 
- http://jenkins.cloudius-systems.com:8080/job/scylla-2.1-ubuntu-deb-16.04-test/4/
- http://jenkins.cloudius-systems.com:8080/job/scylla-2.1-ubuntu-deb-test/label=huginn/5/

**Comment by amoskong** [comment]
Approved by Roy, let's merge it.

image

**Pull request merged**
